model: "dualvae"
batch_size: 8                # Batch size for training
lr: 0.0001                     # Learning rate
epochs: 250                   # Number of training epochs
patience: 15                # Early stopping patience
checkpoints: "./checkpoints/dualvae/"  # Checkpoint save path
train_ratio: 0.8     
val_ratio: 0.2       # Train ratio
kl_beta: 0.001           # Beta KL Loss (used in Optuna)
resize_img: 250
augment: False
device: "cuda"              # Device
architecture: "cuda"        # Model architecture
dataset_path: "../data/FULL_UNIFIED"  # Dataset path
wandb_project: "dual_vae"  # Wandb Project Name
wandb_entity: "imagine-laboratory-conare"  # Wandb Project Entity
seed: 42
codebook_dim: 64
num_embeddings: 128
commitment_cost: 0.25
