# Training Hyperparameters
dataset_path: "/data/oortega/pineapple_960x544.h5"
path_test_ids: "./test_ids.txt"
batch_size: 8
num_workers: 4
lr: 0.0001
epochs: 800
rec_importance: 1
seed: 42

# Model Paths & Checkpoints
chkps_logging_path: "/work/oortega/checkpoints/diffusion/dualvae/" #### This is for DualVAE
vae_chkp: "/work/oortega/checkpoints/dualvae/Codebok_64@Commit_0.25@NumEmb_128/weights_ck_248.pt"

# Early Stopping
patience: -1
es_min_delta: 0.1

# Flags (Store True)
do_wandb: True
non_uniform_sampling: false
attention: false
augment: false
constant_lr: false

# Logging & Tracking
run_name: "DualVAE-DDPM-v1"
wandb_run_id: null
